automate release process
Release process now: run script/release that's all to remember. In interactive (default) mode it will guide through bumping version number, editing CHANGELOG, creating release commit and tag, answer `n` to "Upload to PyPI" question.

- script/release will push new tag to Github
- Github will invoke Travis build hook
- Travis will build and upload PyPI package, granted all tests pass

script/release considers these sources of actual version information:

- python3/httplib2/__init__.py:__version__ = 'foobar'
- git tag in -auto mode (on Travis)
- what user entered in interactive mode

Every commit in every branch gets uploaded to Test PyPI, e.g. https://test.pypi.org/project/httplib2/0.11.1.post1803270210/
Every tagged commit in master gets uploaded to Public PyPI.

https://github.com/httplib2/httplib2/pull/99

diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -12,49 +12,65 @@ test_flags=(
 	tests/
 )
 
-cd "$( dirname "${BASH_SOURCE[0]}" )/.."
-if [[ -n "${CONTINUOUS_INTEGRATION-}" ]] ; then
-	case "${test_group-}" in
-	pep8)
-		if [[ "${TRAVIS_PYTHON_VERSION}" = "2.7" ]] ; then
-			flake8 python2/
-		else
-			flake8 python3/ tests/
+main() {
+	cd "$( dirname "${BASH_SOURCE[0]}" )/.."
+	if [[ -n "${CONTINUOUS_INTEGRATION-}" ]] ; then
+		case "${test_group-}" in
+		pep8)
+			if [[ "${TRAVIS_PYTHON_VERSION}" = "2.7" ]] ; then
+				flake8 python2/
+			else
+				flake8 python3/ tests/
+			fi
+			;;
+		package)
+			# TODO: sdist bdist_wheel
+			# but wheels don't roll well with our 2/3 split code base
+			python setup.py sdist
+			install_check_version "pip"
+			;;
+		*)
+			pip install -e .
+			httplib2_test_still_run_skipped=1 pytest --fulltrace -k test_303 $@ tests/ || true
+			httplib2_test_still_run_skipped=1 pytest --fulltrace -k test_head_301 $@ tests/ || true
+			pytest --fulltrace ${test_flags[@]}
+			;;
+		esac
+	else
+		if [[ ! -d ./venv-27 ]] ; then
+			virtualenv --python=python2.7 ./venv-27
 		fi
-		;;
-	package)
-	    # TODO: sdist bdist_wheel
-	    # but wheels don't roll well with our 2/3 split code base
-		python setup.py sdist
-		pip install dist/httplib2*
-		;;
-	*)
-		pip install -e .
-		httplib2_test_still_run_skipped=1 pytest --fulltrace -k test_303 $@ tests/ || true
-		httplib2_test_still_run_skipped=1 pytest --fulltrace -k test_head_301 $@ tests/ || true
-		pytest --fulltrace ${test_flags[@]}
-		codecov --flags=$(echo $python |tr -d -- '-.')
-		;;
-	esac
-else
-	if [[ ! -d ./venv-27 ]] ; then
-		virtualenv --python=python2.7 ./venv-27
+		if [[ ! -d ./venv-36 ]] ; then
+			virtualenv --python=python3.6 ./venv-36
+		fi
+
 		./venv-27/bin/pip install -e . -r requirements-test.txt
-	fi
-	if [[ ! -d ./venv-36 ]] ; then
-		virtualenv --python=python3.6 ./venv-36
+		./venv-27/bin/pytest ${test_flags[@]}
 		./venv-36/bin/pip install -e . -r requirements-test.txt
+		./venv-36/bin/pytest ${test_flags[@]}
+
+		# FIXME: too many errors
+		# ./venv-27/bin/flake8 python2/
+		# ./venv-36/bin/flake8 python3/ tests/
+
+		# TODO: sdist bdist_wheel
+		# but wheels don't roll well with our 2/3 split code base
+		./venv-36/bin/python setup.py sdist
+		install_check_version "./venv-27/bin/pip"
+		install_check_version "./venv-36/bin/pip"
 	fi
+	rm -rf ./_httplib2_test_cache
+}
 
-	./venv-27/bin/pytest ${test_flags[@]}
-	./venv-36/bin/pytest ${test_flags[@]}
+install_check_version() {
+	local pip="$1"
+	$pip install dist/httplib2*
+	version_source=$(cd python3 ; python3 -Es -c 'import httplib2;print(httplib2.__version__)')
+	version_installed=$($pip show httplib2 |fgrep Version |cut -d' ' -f2)
+	if [[ "$version_source" != "$version_installed" ]] ; then
+		echo "error: installed package version=$version_installed does not match source=$version_source" >&2
+		exit 1
+	fi
+}
 
-	# FIXME: too many errors
-	# ./venv-27/bin/flake8 python2/
-	# ./venv-36/bin/flake8 python3/ tests/
-
-    # TODO: sdist bdist_wheel
-    # but wheels don't roll well with our 2/3 split code base
-	./venv-36/bin/python setup.py sdist
-fi
-rm -rf ./_httplib2_test_cache
+main "$@"
